#!/bin/sh

docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_DELETE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_DELETE_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_FIND
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_FIND_ONE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_FIND_ONE_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_SAVE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_UPDATE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_VALIDATE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_VALIDATE_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic JWKS_FIND_ONE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic JWKS_GET_ONE_RANDOM
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_BLOCK
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_BLOCK_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_DELETE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_DELETE_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_FIND
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_FIND_ONE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_FIND_ONE_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_SAVE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_VALIDATE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_VALIDATE_BY_TOKEN
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND_BY_TELEGRAM_ID
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND_BY_USERNAME
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND_ONE
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_GET
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_PUT
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_SAVE

docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_DELETE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_DELETE_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_FIND.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_FIND_ONE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_FIND_ONE_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_SAVE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_UPDATE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_VALIDATE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic AT_VALIDATE_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic JWKS_FIND_ONE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic JWKS_GET_ONE_RANDOM.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_BLOCK.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_BLOCK_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_DELETE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_DELETE_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_FIND.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_FIND_ONE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_FIND_ONE_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_SAVE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_VALIDATE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic RT_VALIDATE_BY_TOKEN.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND_BY_TELEGRAM_ID.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND_BY_USERNAME.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_FIND_ONE.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_GET.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_PUT.reply
docker-compose exec broker kafka-topics --zookeeper zookeeper:2181 --create --partitions 1 --replication-factor 1 --topic USER_SAVE.reply
